name: pr pipeline

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps: 
            - name: test build
              uses: ./.github/workflows/reusable-build-test.yml
              with: 
                run_tests: true
                python_version: '3.11'
    pr-comment:
        needs: [build-test]
        runs-on: ubuntu-latest
        steps:
            - name: pr-summary
              run: echo "PR checks passed for branch:${{github.head_ref}}"
